spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_employee
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

